import type { NatureArea, CropZone, AgriculturalStat, FloodGauge, MapServiceLayer } from "./mapData";

export const DEFAULT_PROTECTED_AREAS: NatureArea[] = [
  {
    id: "nsg-lampertheimer-altrhein",
    name: "Naturschutzgebiet Lampertheimer Altrhein",
    designation: "nsg",
    municipality: "Lampertheim",
    area_hectares: 516.0,
    legal_ordinance_year: 1927,
    conservation_aims: "Größtes Altrheingebiet Hessens mit Auenwäldern, Verlandungszonen, Brut- und Rastplatz für über 200 Vogelarten (Weißstörche, Silberreiher, Eisvogel).",
    visiting_rules: { leash_required: true, stay_on_paths: true, no_drones: true, no_swimming: true },
    geojson: {
      type: "Polygon",
      coordinates: [[[8.435, 49.585], [8.462, 49.578], [8.472, 49.595], [8.455, 49.610], [8.435, 49.585]]],
    },
    source: "hlnug_natureg",
  },
  {
    id: "nsg-biedensand",
    name: "Naturschutzgebiet Biedensand",
    designation: "nsg",
    municipality: "Lampertheim",
    area_hectares: 250.0,
    legal_ordinance_year: 1984,
    conservation_aims: "Urtümliche Auenlandschaft, Altwasserarme, Amphibienlaichgewässer und Röhrichtbestände.",
    visiting_rules: { leash_required: true, stay_on_paths: true, no_camping: true },
    geojson: {
      type: "Polygon",
      coordinates: [[[8.442, 49.592], [8.458, 49.590], [8.460, 49.603], [8.445, 49.605], [8.442, 49.592]]],
    },
    source: "hlnug_natureg",
  },
  {
    id: "ffh-buerstaedter-wald",
    name: "FFH-Gebiet Bürstädter Wald / Lorcher Wald",
    designation: "ffh",
    municipality: "Bürstadt",
    area_hectares: 420.0,
    legal_ordinance_year: 2000,
    conservation_aims: "Naturnahe Hartholz- und Eichenmischwälder, Lebensraum für Hirschkäfer, Bechsteinfledermaus und Mittelspecht.",
    visiting_rules: { stay_on_paths: true, leash_required: true },
    geojson: {
      type: "Polygon",
      coordinates: [[[8.468, 49.635], [8.498, 49.638], [8.495, 49.655], [8.470, 49.650], [8.468, 49.635]]],
    },
    source: "hlnug_natureg",
  },
  {
    id: "nsg-weschnitzinsel",
    name: "Naturschutzgebiet Weschnitzinsel Lorsch",
    designation: "nsg",
    municipality: "Biblis / Lorsch",
    area_hectares: 198.0,
    legal_ordinance_year: 1979,
    conservation_aims: "Feuchtwiesen, Storchwiesen und dynamische Auenvegetation entlang der Weschnitz.",
    visiting_rules: { stay_on_paths: true, leash_required: true },
    geojson: {
      type: "Polygon",
      coordinates: [[[8.545, 49.650], [8.572, 49.655], [8.568, 49.670], [8.540, 49.665], [8.545, 49.650]]],
    },
    source: "hlnug_natureg",
  },
  {
    id: "wsg-ried-zone-2",
    name: "Wasserschutzgebiet Hessisches Ried (Zone II/III)",
    designation: "wsg",
    municipality: "Bürstadt",
    area_hectares: 1850.0,
    legal_ordinance_year: 1995,
    conservation_aims: "Zentrales Grundwasserschutzgebiet zur Sicherung der regionalen Trinkwasserversorgung und Vermeidung von Schadstoffeinträgen.",
    visiting_rules: { groundwater_protection: true, commercial_restrictions: true },
    geojson: {
      type: "Polygon",
      coordinates: [[[8.440, 49.620], [8.485, 49.622], [8.480, 49.660], [8.435, 49.655], [8.440, 49.620]]],
    },
    source: "hlnug_natureg",
  },
];

export const DEFAULT_AGRICULTURE_STATS: AgriculturalStat[] = [
  { municipality: "Bürstadt", year: 2025, crop_family: "sonderkultur", crop_name: "Spargel (Weiß- & Grünspargel)", area_hectares: 485.0, percentage_of_agricultural_land: 24.2 },
  { municipality: "Bürstadt", year: 2025, crop_family: "gemuese", crop_name: "Freilandgemüse (Zwiebeln, Möhren, Salat)", area_hectares: 540.0, percentage_of_agricultural_land: 27.0 },
  { municipality: "Bürstadt", year: 2025, crop_family: "sonderkultur", crop_name: "Erdbeeren & Beerenobst", area_hectares: 165.0, percentage_of_agricultural_land: 8.2 },
  { municipality: "Bürstadt", year: 2025, crop_family: "getreide", crop_name: "Winterweizen & Gerste", area_hectares: 390.0, percentage_of_agricultural_land: 19.5 },
  { municipality: "Bürstadt", year: 2025, crop_family: "getreide", crop_name: "Körner- & Silomais", area_hectares: 240.0, percentage_of_agricultural_land: 12.0 },
  { municipality: "Bürstadt", year: 2025, crop_family: "sonderkultur", crop_name: "Tabakanbau (Historischer Schauanbau)", area_hectares: 15.0, percentage_of_agricultural_land: 0.8 },
  { municipality: "Bürstadt", year: 2025, crop_family: "oelfrucht", crop_name: "Zuckerrüben & Raps", area_hectares: 165.0, percentage_of_agricultural_land: 8.3 },
  { municipality: "Lampertheim", year: 2025, crop_family: "sonderkultur", crop_name: "Spargel (Spargelstadt Lampertheim)", area_hectares: 620.0, percentage_of_agricultural_land: 26.5 },
  { municipality: "Lampertheim", year: 2025, crop_family: "gemuese", crop_name: "Freilandgemüse (Bundzwiebeln, Radieschen)", area_hectares: 680.0, percentage_of_agricultural_land: 29.0 },
  { municipality: "Lampertheim", year: 2025, crop_family: "sonderkultur", crop_name: "Erdbeeren & Beerenobst", area_hectares: 210.0, percentage_of_agricultural_land: 9.0 },
  { municipality: "Lampertheim", year: 2025, crop_family: "getreide", crop_name: "Winterweizen", area_hectares: 430.0, percentage_of_agricultural_land: 18.4 },
  { municipality: "Lampertheim", year: 2025, crop_family: "getreide", crop_name: "Silomais", area_hectares: 260.0, percentage_of_agricultural_land: 11.1 },
  { municipality: "Lampertheim", year: 2025, crop_family: "sonderkultur", crop_name: "Tabakanbau (Kulturbeleg)", area_hectares: 12.0, percentage_of_agricultural_land: 0.5 },
  { municipality: "Lampertheim", year: 2025, crop_family: "oelfrucht", crop_name: "Zuckerrüben", area_hectares: 130.0, percentage_of_agricultural_land: 5.5 },
];

export const DEFAULT_CROP_ZONES: CropZone[] = [
  {
    id: "crop-bst-spargel-boxheimer",
    municipality: "Bürstadt",
    crop_name: "Spargel",
    crop_family: "sonderkultur",
    year: 2025,
    area_hectares: 42.5,
    irrigation_demand_class: "high",
    geojson: { type: "Polygon", coordinates: [[[8.468, 49.638], [8.482, 49.640], [8.480, 49.646], [8.465, 49.644], [8.468, 49.638]]] },
  },
  {
    id: "crop-bst-gemuese-nord",
    municipality: "Bürstadt",
    crop_name: "Freilandgemüse (Zwiebeln & Möhren)",
    crop_family: "gemuese",
    year: 2025,
    area_hectares: 38.0,
    irrigation_demand_class: "high",
    geojson: { type: "Polygon", coordinates: [[[8.452, 49.652], [8.468, 49.654], [8.466, 49.660], [8.450, 49.658], [8.452, 49.652]]] },
  },
  {
    id: "crop-la-spargel-heide",
    municipality: "Lampertheim",
    crop_name: "Spargel",
    crop_family: "sonderkultur",
    year: 2025,
    area_hectares: 55.0,
    irrigation_demand_class: "high",
    geojson: { type: "Polygon", coordinates: [[[8.472, 49.605], [8.490, 49.607], [8.488, 49.615], [8.470, 49.613], [8.472, 49.605]]] },
  },
  {
    id: "crop-la-erdbeeren-sued",
    municipality: "Lampertheim",
    crop_name: "Erdbeeren",
    crop_family: "sonderkultur",
    year: 2025,
    area_hectares: 24.0,
    irrigation_demand_class: "high",
    geojson: { type: "Polygon", coordinates: [[[8.460, 49.588], [8.475, 49.589], [8.473, 49.596], [8.458, 49.594], [8.460, 49.588]]] },
  },
  {
    id: "crop-bib-mais-flur",
    municipality: "Biblis",
    crop_name: "Körnermais",
    crop_family: "getreide",
    year: 2025,
    area_hectares: 31.0,
    irrigation_demand_class: "medium",
    geojson: { type: "Polygon", coordinates: [[[8.435, 49.675], [8.450, 49.676], [8.448, 49.683], [8.432, 49.681], [8.435, 49.675]]] },
  },
];

export const DEFAULT_FLOOD_GAUGES: FloodGauge[] = [
  {
    id: "pegel-rhein-worms",
    name: "Rheinpegel Worms (km 443.4)",
    water_body: "Rhein",
    municipality: "Worms / Riedufer",
    latitude: 49.6315,
    longitude: 8.3755,
    current_level_m: 2.78,
    discharge_m3_s: 1420.0,
    alarm_level_1_m: 4.50,
    alarm_level_2_m: 5.50,
    alarm_level_3_m: 6.50,
    status: "normal",
    source: "pegelonline_wsv",
    updated_at: new Date().toISOString(),
  },
  {
    id: "pegel-weschnitz-lorsch",
    name: "Weschnitzpegel Lorsch",
    water_body: "Weschnitz",
    municipality: "Lorsch / Bürstadt Ost",
    latitude: 49.6542,
    longitude: 8.5670,
    current_level_m: 0.82,
    discharge_m3_s: 4.8,
    alarm_level_1_m: 1.80,
    alarm_level_2_m: 2.30,
    alarm_level_3_m: 2.80,
    status: "normal",
    source: "gkd_hessen",
    updated_at: new Date().toISOString(),
  },
];

export const DEFAULT_MAP_SERVICES: MapServiceLayer[] = [
  {
    id: "wms-starkregen-hessen",
    title: "Starkregengefahrenkarte Hessen (KLIMPRAX)",
    category: "starkregen",
    service_type: "WMS",
    wms_url: "https://gds.hessen.de/wms/hlug_starkregen",
    layer_name: "starkregen_gefahrenkarte",
    attribution: "© HLNUG / Geoportal Hessen (dl-de/by-2-0)",
    default_opacity: 0.60,
    min_zoom: 10,
    max_zoom: 19,
  },
  {
    id: "wms-hochwasser-hq100",
    title: "Überschwemmungsgebiete HQ100 (HQ100 / HQextrem)",
    category: "flood_risk",
    service_type: "WMS",
    wms_url: "https://gds.hessen.de/wms/hlug_hwgk_ueberschwemmungsgebiete",
    layer_name: "ueberschwemmungsgebiete_hq100",
    attribution: "© HLNUG / Hessische Wasserwirtschaft",
    default_opacity: 0.55,
    min_zoom: 10,
    max_zoom: 19,
  },
];
